### ISSUE TITLE
Allow wallet to define its policy about response encryption

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#171]
So far the library tries to match the issuer's requirements for the encryption of the response (that carries the issued credential).
In general VCI allows the issuer to chose one of the following options:
- **Not Used** (`credential_response_encryption` is not provided to issuer's metadata)
- **Supported but not required** (`credential_response_encryption` is present and `encryption_required` is `false`)
- **Required** (`credential_response_encryption` is present and `encryption_required` is `true`)

Wallet could also define  a similar policy independently of the issuer's choice. During resolution of a credential offer there could be a step to assure that those two policies are compatible and proceed with the issuance.

 The wallet's policy can be the following:
 - **Required** 
 - **Supported**
 
|                                             |  Required  | Supported  |
|--------------------------------------|---------------|----------------|
| Not used                              |  Boom       |   No encryption   |
| Supported but not required  |  Encrypt   |  Try to encrypt. Fallback to no encryption    |
| Required                              |  Encrypt   |   Encrypt      |

**Comment by babisRoutis** [comment]
@vafeini Can you check this? Any thoughts?

**Comment by vafeini** [comment]
In a future version of the lib we may consider to perform the policy compliance checks more in advance, for example when Issuer component is created and we have the issuing service metadata. Not sure if this compliance check is the library's responsibility but maybe it should give a way to perform it in advance before reaching the issuance request step.

**Comment by babisRoutis** [comment]
> In a future version of the lib we may consider to perform the policy compliance checks more in advance, for example when Issuer component is created and we have the issuing service metadata. Not sure if this compliance check is the library's responsibility but maybe it should give a way to perform it in advance before reaching the issuance request step.

Why not included now?

To my understanding all it takes is to :

- [ ] Change the evaluation of [responseEncryptionSpec](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/00b6d02531d2c2b59fef8e4d8e41af47d0db27f1/src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/RequestIssuanceImpl.kt#L30C17-L30C39). Instead of lazily evaluating it, we should evaluated upon initialization
- [ ] Let the [Issuer.make](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/00b6d02531d2c2b59fef8e4d8e41af47d0db27f1/src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt#L52) factory method return a `Result<Issuer>` instead of an `Issuer`

**Comment by vafeini** [comment]
I prefere the first approach, meaning doing the compatibility check upon the creation of the issuer ([Issuer.make](https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/00b6d02531d2c2b59fef8e4d8e41af47d0db27f1/src/main/kotlin/eu/europa/ec/eudi/openid4vci/Issuer.kt#L52)) and leave the `Issuer.metaData` as a utility method to retrive the metadata of the issuer for any use.
