### ISSUE TITLE
Support DPoP

### ISSUE THREAD

**Issue by babisRoutis** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#188]
[RFC9449](https://www.rfc-editor.org/rfc/rfc9449.html#name-concept) defines  `DPoP JWT` as a way to:
 - Ensure that an issued `access_token` is used by the client (wallet) that requested it, and
 - Constraint the usage of the `access_token`

This DPoP (demonstration of Proof of Possession) must not be confused with Proof Of Possession that may be used within the credential request.

The basic requirement is:

**Token Request**
- Lib can place a request against the Token Endpoint (to obtain access_token) adding as an HTTP header a specially prepared DPoP JWT. `htm` and `htu` should point to token endpoint method and URL (no fragment, no query)
- In case OAUTH2 server supports DPoP, it will reply with
   -  `token_type` equal to `DPoP`, otherwise
   -    `bearer`
- Library should store this information (whether DPoP was supported)   

**Placing a call to Issuer Endpoints**
For accessing one of the endpoints of the issuer (that require `access_token`: issuance, batch, deferred, notification) , library must 
- generate a new DPoP JWT . `htm` and `htu` point to the method and endpoint used
- add the DPoP as an HTTP header
- Change the way access token is placed as a header. Instead of `Authorization bearer <access_token>` to `Authorization DPoP <access_token>'

**Comment by ydanneg** [comment]
Support of DPoP was my next Issue report :) 
Now i found this issue and very glad to see it in progress.. will try to test it

**Comment by babisRoutis** [comment]
> Support of DPoP was my next Issue report :) Now i found this issue and very glad to see it in progress.. will try to test it

Hi @ydanneg 
You can watch the progress or findings on the PR  https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/pull/191
My problem is how to test this. Do you happened to have a DPoP-enabled  Credential issuer? :smile:

**Comment by babisRoutis** [comment]
>  I will report soon..

@ydanneg Let me guess : attestation-based authentication

**Comment by ydanneg** [comment]
> >  I will report soon..
> 
> @ydanneg Let me guess : attestation-based authentication

I hope it will come soon into your roadmap :)

But actually I meant to report to their repo.

**Comment by babisRoutis** [comment]
@ydanneg That would be great Gennadi !
