### ISSUE TITLE
TokenResponse expires_in property should be optional

### ISSUE THREAD

**Issue by ydanneg** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#196]
`expires_in` should be nullable
https://github.com/eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt/blob/31bd5d31a06340b3f1663643110aecd699930f56/src/main/kotlin/eu/europa/ec/eudi/openid4vci/internal/AuthorizationServerClient.kt#L86

ref: https://www.rfc-editor.org/rfc/rfc6749.html#section-4.2.2

**Comment by babisRoutis** [comment]
@ydanneg Thanks
