### ISSUE TITLE
oauth-authorization-server related issue,  not able to reach the correct endpoint

### ISSUE THREAD

**Issue by cindy-chin** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#224]
Hi, I think there might be an issue that cause reference wallet related to “.well-known/oauth-authorization-server”.
The behaviour of current reference wallet appending “.well-known/oauth-authorization-server” to a url with path components different with what specs have been stated.
Let's say we have https://example.com/path1/path2
Current behaviour of reference wallet is appending it right behind the url like :https://example.com/path1/path2/.well-known/oauth-authorization-server

According to the spec https://www.rfc-editor.org/rfc/rfc8414.html#section-3
“.well-known/oauth-authorization-server” need to be inserted after removing the path components first. e.g : https://example.com/.well-known/oauth-authorization-server/path1/path2

**Comment by dtsiflit** [comment]
Big thanks, @cindy-chin , for flagging this. I've moved it to this repository since it seems like a better fit for functions related to specifications.

**Comment by babisRoutis** [comment]
Hi @cindy-chin 

Clearly, you are right. This is a bug that will be addressed.

FYI: 
- Some popular libraries (for instance Nimbus) resolves not in a compliant way the OAUTH2/OIDC metadata 
- Some popular IdP servers also expose their metadata endpoint at then end of their issuer claim

So, it is not uncommon to have to deal with not strictly compliant cases.

For this reason, we will implement some fallback logic
That is, for a IdP having an issuer claim http://foo.bar/path1/path2
Library will check
- http://foo.bar/.well-known/openid-configuration/path1/path2  (compliant)
- http://foo.bar/path1/path2/.well-known/openid-configuration  (not compliant, but common)
- http://foo.bar/.well-known/oauth-authorization-server/path1/path2 (compliant)
- http://foo.bar/path1/path2/.well-known/oauth-authorization-server (not compliant, but common)

**Comment by babisRoutis** [comment]
@dtsiflit Please schedule a similar fix for iOS

By the way:
- The [metadata](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-credential-issuer-metadata-) of the Credential Issuer DON'T use the same convention. 
- The [metadata](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-03.html#name-jwt-vc-issuer-metadata) of a  SD-JWT-VC issuer DO use the same convention.
