### ISSUE TITLE
Support order parameter in IETF SD-JWT VC credential configuration

### ISSUE THREAD

**Issue by spheroid** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#321]
Currently only `MsoMdocCredential` configuration supports the `order` parameter defined in OpenID4VCI draft 14, while it's also defined for IETF SD-JWT VC configuration in [appendix A.3.2](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#appendix-A.3.2-3.3).

Is this left out by design or is it just something you haven't gotten around to do yet?

**Comment by babisRoutis** [comment]
Hi @spheroid 

Somehow, we missed it. 
Thanks for reporting this.
