### ISSUE TITLE
Add support for Resource Server-Provided Nonce

### ISSUE THREAD

**Issue by dzarras** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#334]
Affects:
- Credential endpoint
- Deferred endpoint
- Notification endpoint
- c_nonce endpoint (introduced with latest OpenId4VCI)

Reference: [Resource Server-Provided Nonce](https://datatracker.ietf.org/doc/html/rfc9449#name-resource-server-provided-no)

**Comment by daniel-idrees** [comment]
Thank you for resolving this quickly!
