### ISSUE TITLE
iss claim in jwt proof type must be omitted for pre-authorized code flow according to the openid4vci spec

### ISSUE THREAD

**Issue by khaingphyo** [eu-digital-identity-wallet/eudi-lib-jvm-openid4vci-kt#338]
iss: OPTIONAL (string). The value of this claim MUST be the client_id of the Client making the Credential request. This claim MUST be omitted if the access token authorizing the issuance call was obtained from a Pre-Authorized Code Flow through anonymous access to the token endpoint.

https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-14.html#section-7.2.1.1-2.2.1

**Comment by babisRoutis** [comment]
Dear @khaingphyo 
Thanks for reporting this.
